### ISSUE TITLE
[question] What the difference between netty-jaxrs and jersey-container-netty-http ?

### ISSUE THREAD

**Issue by volyx** [kpavlov/netty-jaxrs#5]
I'm thinking about the raw implementation of the whole Jax-RS Specification and have found your repository. 

jersey-container-netty-http -  https://github.com/eclipse-ee4j/jersey/tree/master/containers/netty-http

As I see, the goal of those projects is the same, but maybe I have missed something

**Comment by kpavlov** [comment]
Hi, I didn't find that library when I needed to implement JAXRS endpoint with netty. I don't know, which library is the best now. I implemented only basics and not sure if all the use-cases ate covered.
